<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>


</template>

<script>
  import {
    defineComponent,
    toRefs,
    reactive,
    getCurrentInstance
  }
  from 'vue'
  export default defineComponent({
    components: {},
    props: {},
    setup() {

      return {
        ...toRefs(state),
        submitForm,
        resetForm
      }
    }
  })

</script>

<style lang="scss">


</style>
